### ISSUE TITLE
How is the final .stl file generated from nx.Graph()?

### ISSUE THREAD

**Issue by Paddy-Xu** [nmaftoon/VesselGen#1]
Hi,

Thanks for the interesting work and making code available. However, I am confused about how to generate the final .stl file of the vessels. If I understand correctly, the vascular network is represented as a  nx.Graph() object with connectivity information as well as node and edge features representing radius, length, Strahler's order etc., However, I am wondering how the final mesh with different cylinders of all the branches are created and connected and then saved to a stl file?

Thank you in advance!

**Comment by Abdul-Hannan-Faruqi** [comment]
Hello!

Thank you for your interest in our work. 
You may use the files in the Visualization folder and follow the instructions to generate the 3D model in AutoDesk Fusion360. You may export this model to any of the available formats.
